version: '3.8'

services:
  php-8:
    build:
      context: .
      dockerfile: php_configs/php8.1/php8.Dockerfile
    container_name: php8-container
    volumes:
      - ../www/spa-fnb-retail:/var/www/spa-fnb-retail
    networks:
      - app-network

  php-7:
    build:
      context: .
      dockerfile: php_configs/php7.4/php7.Dockerfile
    container_name: php7-container
    volumes:
      - ../www/posapp-crm:/var/www/posapp-crm
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/templates:/etc/nginx/templates
#      - ./src:/var/www
      - ../www:/var/www
    working_dir: /var/www
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - php-8
      - php-7
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
