services:
  nginx:
    image: long301001/server-php:nginx-amd
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server:/var/www
      - ./scripts:/var/scripts
      - ./nginx/examples:/etc/nginx/examples
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/logs:/var/log/nginx
      - ./env.json:/var/environment/env.json
    command: ["sh", "-c", "/var/scripts/auto-add-template.sh && /var/scripts/entrypoint.sh"]
    depends_on:
      - php-8
      - php-7
    networks:
      - app-network

  php-8:
    image: long301001/server-php:php8.2-amd
    container_name: php8_container
    volumes:
      - ./server/source_php8.2:/var/www/source_php8.2
      - ./scripts:/var/scripts
      - ./configs/php8/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf
    working_dir: /var/www/source_php8.2
    networks:
      - app-network

  php-7:
     image: long301001/server-php:php7.4-amd
     container_name: php7_container
     volumes:
       - ./server/source_php7.4:/var/www/source_php7.4
       - ./scripts:/var/scripts
       - ./configs/php7.4/php.ini:/usr/local/etc/php/php.ini
     working_dir: /var/www/source_php7.4
     networks:
       - app-network

  redis:
    image: long301001/server-php:redis-amd
    container_name: redis_container
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql:
    image: long301001/server-php:mysql-amd
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Cho phép mật khẩu trống cho root
      MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"  # Ánh xạ cổng 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # Cổng AMQP (cho ứng dụng kết nối)
      - "15672:15672" # Cổng UI Web
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app-network

volumes:
  mysql-data:  # Khai báo volume mysql-data
    driver: local  # Dùng driver local (mặc định)
    name: mysql-data  # Tên volume
  redis-data:
    driver: local
    name: redis-data

networks:
  app-network:
    driver: bridge
