; Cấu hình Xdebug
xdebug.mode=develop,debug
xdebug.start_with_request=yes

; Kết nối IDE (VD: PhpStorm, VSCode)
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; Cho phép log
xdebug.log=/tmp/xdebug.log
