services:
  mailpit:
    image: multi-php-local:mailpit
    profiles: ["mailpit"]
    build:
      context: .
      dockerfile: ./docker_files/mailpit.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: mailpit_container
    hostname: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
