services:
  minio:
    image: long301001/multi-php-docker:minio
    profiles: ["minio"]
    build:
      context: .
      dockerfile: ./docker_files/minio.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: minio_container
    hostname: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

volumes:
  minio-data:
    driver: local
    name: minio-data

networks:
  app-network:
    driver: bridge
