services:
  php-8.2:
    profiles: ["php-8.2"]
    image: long301001/multi-php-docker:php-8.2
    container_name: php8.2_container
    volumes:
      - ./server/source_php8.2:/var/www/source_php8.2
      - ./scripts:/var/scripts
      - ./configs/php8/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf
    working_dir: /var/www/source_php8.2
    networks:
      - app-network

  supervisor-8.2:
    profiles: ["supervisor-8.2"]
    image: long301001/multi-php-docker:php-8.2
    container_name: supervisor82_container
    volumes:
      - ./server/source_php8.2:/var/www/source_php8.2
      - ./scripts:/var/scripts
      - ./configs/php8/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./configs/supervisor.d/php8.2:/etc/supervisor/conf.d:ro
      - ./logs/supervisor-8.2:/var/log/supervisor
    working_dir: /var/www/source_php8.2
    command: ["/var/scripts/docker/supervisord.sh"]
    depends_on:
      mysql:
        condition: service_started
        required: false
      redis:
        condition: service_started
        required: false
      rabbitmq:
        condition: service_started
        required: false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
