services:
  php-7.4:
    profiles: ["php-7.4"]
    image: long301001/multi-php-docker:php-7.4
    build:
      context: .
      dockerfile: ./docker_files/php7.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: php7.4_container
    volumes:
      - ./server/source_php7.4:/var/www/source_php7.4
      - ./scripts:/var/scripts
      - ./configs/php7.4/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/source_php7.4
    networks:
      - app-network

  supervisor-7.4:
    profiles: ["php-7.4"]
    image: long301001/multi-php-docker:php-7.4
    container_name: supervisor74_container
    volumes:
      - ./server/source_php7.4:/var/www/source_php7.4
      - ./scripts:/var/scripts
      - ./configs/php7.4/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./configs/supervisor.d/php7.4:/etc/supervisor/conf.d:ro
      - ./logs/supervisor-7.4:/var/log/supervisor
    working_dir: /var/www/source_php7.4
    command: ["/var/scripts/supervisord.sh"]
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
