services:
  php-8.5:
    build:
      context: ./docker_files
      dockerfile: php8.5.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: long301001/multi-php-docker:php-8.5
    container_name: php8.5_container
    volumes:
      - ./server/source_php8.5:/var/www/source_php8.5
      - ./scripts:/var/scripts
      - ./configs/php8.5/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf
    working_dir: /var/www/source_php8.5
    networks:
      - app-network

  supervisor-8.5:
    profiles: ["supervisor-8.5"]
    image: long301001/multi-php-docker:php-8.5
    container_name: supervisor85_container
    volumes:
      - ./server/source_php8.5:/var/www/source_php8.5
      - ./scripts:/var/scripts
      - ./configs/php8.5/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisord.conf:/etc/supervisord.conf:ro
      - ./configs/supervisor.d/php8.5:/etc/supervisor/conf.d:ro
      - ./logs/supervisor-8.5:/var/log/supervisor
    working_dir: /var/www/source_php8.5
    command: ["/var/scripts/docker/supervisord.sh"]
    depends_on:
      mysql:
        condition: service_started
        required: false
      redis:
        condition: service_started
        required: false
      rabbitmq:
        condition: service_started
        required: false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
