services:
  rabbitmq:
    image: long301001/multi-php-docker:rabbitmq-3-management
    build:
      context: .
      dockerfile: ./docker_files/rabbitMQ.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
