# Nginx main configuration

worker_processes auto;

# Sử dụng phần 'events' bắt buộc
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    proxy_buffers 16 64k;
    proxy_buffer_size 128k;
    fastcgi_read_timeout 300;

    # Bao gồm các tệp cấu hình server
    include /etc/nginx/conf.d/*.conf;
}
