[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock   ; Đường dẫn socket cho supervisorctl
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php_worker]
command=php /var/www/hola-framework/cli.php queue:run
numprocs=3
process_name=%(program_name)s_%(process_num)s
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/worker.log
stderr_logfile=/var/log/supervisor/worker_error.log
